apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  key: nginx.conf
  value: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }
