imageTag: 8.5.1
# resources:
#   requests:
#     cpu: "50m"
#     memory: "256M"
#   limits:
#     cpu: "500m"
#     memory: "512M"
# service:
#   type: ClusterIP
# extraEnvs:
#   - name: "ELASTICSEARCH_USERNAME"
#     value: "elastic"
#   - name: "ELASTICSEARCH_PASSWORD"
#     valueFrom:
#       secretKeyRef:
#         name: elasticsearch-master-credentials
#         key: password
# - name: "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES"
#   value: /usr/share/kibana/config/certs/ca.crt
# secretMounts:
#   - name: elasticsearch-certs
#     secretName: elasticsearch-master-certs
#     path: /usr/share/kibana/config/custom-certs
