apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: my-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - "argocd.harishshetty.xyz"
  rules:
    - backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: my-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - "grafana.harishshetty.xyz"
  rules:
    - backendRefs:
        - name: grafana
          namespace: monitoring
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app1-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: my-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - "app1.harishshetty.xyz"
  rules:
    - backendRefs:
        - name: app1-service
          namespace: default
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app2-route
  namespace: nginx-gateway
spec:
  parentRefs:
    - name: my-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - "app2.harishshetty.xyz"
  rules:
    - backendRefs:
        - name: app2-service
          namespace: default
          port: 80
